version: '3.8'

services:
  rentbot:
    image: rentbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/data/rentbot.db
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}