spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/sqlite
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:rentbot.db}
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false #Turn it on only when you need for analysing queries. Do not leave it on!
    show-sql: false #Turn it on only when you need for analysing queries. Do not leave it on!

application:
  telegram:
    token: ${TELEGRAM_TOKEN}

logging:
  level:
    org:
      asynchttpclient:
        netty:
          handler: error
      openqa:
        selenium: error