INSERT INTO districts(name)
VALUES ('Antakalnis'),
       ('Baltupiai'),
       ('Buivydiškės'),
       ('Bukčiai'),
       ('Fabijoniškės'),
       ('Filaretai'),
       ('Grigiškės'),
       ('Jeruzalė'),
       ('Justiniškės'),
       ('Karoliniškės'),
       ('Lazdynai'),
       ('Lazdynėliai'),
       ('Markučiai'),
       ('Naujamiestis'),
       ('Naujininkai'),
       ('Naujoji Vilnia'),
       ('Pašilaičiai'),
       ('Paupys'),
       ('Pavilnys'),
       ('Pilaitė'),
       ('Rasos'),
       ('Santariškės'),
       ('Saulėtekis'),
       ('Senamiestis'),
       ('Šeškinė'),
       ('Šiaurės miestelis'),
       ('Šnipiškės'),
       ('Užupis'),
       ('Verkiai'),
       ('Vilkpėdė'),
       ('Viršuliškės'),
       ('Visoriai'),
       ('Žemieji Paneriai'),
       ('Žirmūnai'),
       ('Žvėrynas')